#+STARTUP: content hideblocks
#+TODO: TASK(t!) | DONE(d) CANCEL(c)
#+TODO: BUG(b!) | FIXED(f) REJECT(r)

* Архив задач

** DONE Придумать формат файла настроек
   CLOSED: [2018-08-31 Пт 23:04]
   :PROPERTIES:
   :issue_id: 1
   :issue_type: task
   :ARCHIVE_TIME: 2018-08-31 Пт 23:05
   :ARCHIVE_FILE: ~/prog/projects/python/buman/tasks/tasks.org
   :ARCHIVE_OLPATH: Задачи
   :ARCHIVE_CATEGORY: tasks
   :ARCHIVE_TODO: DONE
   :END:
   [2018-07-06 Пт]

   Файл состоит из записей. Запись определяется фигурными
   скобками. Внутри записи (внутри фигурных скобок) на разных строках
   стоят (источник, приёмник, опции). Источник - директория или файл;
   приёмник - директория или файл; опции - список опций через
   двоеточие. Опции могут параметризоваться через равно.

   Пример бэкапа одного файла и одной директории:
   Файл сжимается и шифруется, для результата создаётся хеш и кладётся
   рядом в текстовом файле.
   Директория просто копируется, создаются хеши всех файлов в ней и их
   список кладётся рядом в текстовом файле.
   #+BEGIN_EXAMPLE
     {
         /path/to/source/file
         /path/to/destination/directory
         arch=bzip2:hash=md5:cypher=aes
     }
     {
         /path/to/source/directory
         /path/to/destination/directory
         hash=md5
     }
   #+END_EXAMPLE

   [2018-07-07 Сб]

   Нужно рассмотреть противоречия в конфигурации, когда записи
   противоречат друг другу и когда внутри записи поля противоречат
   друг другу.

   Ещё можно сделать так, чтобы источников и приёмников было несколько
   в одной записи:
   Два разных файла кладутся в каждую из директорий.
   #+BEGIN_EXAMPLE
     {
         src=/path/to/source/file1
         src=/path/to/source/file2
         dst=/path/to/destination/directory1
         dst=/path/to/destination/directory2
         opt=arch:hash
     }
   #+END_EXAMPLE

   Ещё можно ввести синтаксис для раздельной записи опций:
   Параметры одной опции можно последовательно аккумулировать.
   #+BEGIN_EXAMPLE
     {
         src=/path/to/source/file
         dst=/path/to/destination/directory
         opt=arch=bzip2:hash=md5
         opt=cypher=aes
         opt=cypher=256bits
     }
   #+END_EXAMPLE

   [2018-07-08 Вс]

   Добавить имя для записи, чтобы при выводе в консоль и логи можно
   было выводить только имя записи, сократив количество информации.

   Добавить пункт для логгирования. У логгирования есть несколько
   состояний, одно из них требует смены имени файла, поэтому должна
   быть отдельная опция, куда записывается путь к лог-файлу.

* Архив багов

* Архив окружения
